using System.Security.Cryptography;
using System.Text;

namespace EngineeringCouncil.Core.Domain;

/// <summary>
/// Stable identity for graph cache entries that represents the SOURCE SNAPSHOT
/// Graphify analyzes, not artifacts generated by Council/OpenCode during analysis.
///
/// Identity semantics:
///   Git, clean tracked source:  GRAPH-{commitSha}  (stable across Council runs)
///   Git, tracked modifications: GRAPH-{commitSha}-dirty-{hash of tracked modifications}
///   Non-Git:                    GRAPH-{content hash excluding known generated artifacts}
///
/// This ensures Council/OpenCode-generated output files (architecture_observations.json,
/// security_observations.json, graphify-out/, engineering-review-package.json, etc.)
/// never invalidate the graph cache.
/// </summary>
public static class GraphCacheIdentity
{
    /// <summary>
    /// Directory names that are Council/OpenCode-generated artifacts.
    /// Excluded from non-Git content fingerprint.
    /// </summary>
    private static readonly HashSet<string> IgnoredArtifactDirectories = new(StringComparer.OrdinalIgnoreCase)
    {
        "graphify-out"
    };

    /// <summary>
    /// Root-level files that are Council/OpenCode-generated artifacts.
    /// Excluded from non-Git content fingerprint.
    /// </summary>
    private static readonly HashSet<string> IgnoredArtifactFiles = new(StringComparer.OrdinalIgnoreCase)
    {
        "architecture_observations.json",
        "security_observations.json",
        "engineering-review-package.json"
    };

    /// <summary>
    /// Computes a stable graph cache identity from the repository snapshot
    /// and pre-computed Git working tree status.
    /// </summary>
    /// <param name="repository">The repository snapshot.</param>
    /// <param name="isCleanGitTree">
    /// True if the Git working tree is clean (no tracked modifications).
    /// Null if the repository is not a Git repository.
    /// </param>
    /// <param name="modifiedTrackedFiles">
    /// List of tracked file paths with modifications (relative paths).
    /// Empty if clean or non-Git. Used to compute dirty hash.
    /// </param>
    public static string Compute(
        RepositorySnapshot repository,
        bool? isCleanGitTree,
        IReadOnlyList<string>? modifiedTrackedFiles = null)
    {
        // Case A: Git repository, clean tracked source
        if (repository.Commit is { Length: > 0 } commit && isCleanGitTree == true)
        {
            return $"GRAPH-{commit}";
        }

        // Case B: Git repository, tracked modifications
        if (repository.Commit is { Length: > 0 } commitSha && isCleanGitTree == false)
        {
            var modFiles = modifiedTrackedFiles ?? [];
            if (modFiles.Count == 0)
            {
                // No explicit modification list — fall back to commit + content hash
                // of all non-artifact files (conservative)
                var contentHash = ComputeContentHashExcludingArtifacts(repository);
                return $"GRAPH-{commitSha}-dirty-{contentHash}";
            }

            var modHash = ComputeModificationHash(modFiles);
            return $"GRAPH-{commitSha}-dirty-{modHash}";
        }

        // Case D: Non-Git repository — deterministic content fingerprint
        return $"GRAPH-{ComputeContentHashExcludingArtifacts(repository)}";
    }

    /// <summary>
    /// Overload for non-Git or when Git status is not probed.
    /// Uses commit SHA if available, otherwise content hash.
    /// </summary>
    public static string Compute(RepositorySnapshot repository)
        => Compute(repository, isCleanGitTree: null);

    /// <summary>
    /// Hashes tracked modification file paths to produce a deterministic dirty marker.
    /// </summary>
    private static string ComputeModificationHash(IReadOnlyList<string> modifiedFiles)
    {
        var sb = new StringBuilder();
        foreach (var path in modifiedFiles.OrderBy(p => p, StringComparer.Ordinal))
        {
            sb.Append(path).Append('\0');
        }

        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(sb.ToString()));
        return Convert.ToHexString(hash)[..12].ToLowerInvariant();
    }

    /// <summary>
    /// Content-based fingerprint for non-Git repositories.
    /// Excludes known generated artifact paths.
    /// </summary>
    private static string ComputeContentHashExcludingArtifacts(RepositorySnapshot repository)
    {
        var sb = new StringBuilder();
        foreach (var file in repository.Files
                     .Where(f => !IsGeneratedArtifact(f.RelativePath))
                     .OrderBy(f => f.RelativePath, StringComparer.Ordinal))
        {
            sb.Append(file.RelativePath).Append('\0');
            sb.Append(file.SizeBytes).Append('\0');
        }

        if (sb.Length == 0)
            return "empty";

        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(sb.ToString()));
        return Convert.ToHexString(hash)[..12].ToLowerInvariant();
    }

    /// <summary>
    /// Returns true if the relative path is a Council/OpenCode-generated artifact.
    /// </summary>
    public static bool IsGeneratedArtifact(string relativePath)
    {
        var normalizedPath = relativePath.Replace('/', Path.DirectorySeparatorChar);
        var fileName = Path.GetFileName(normalizedPath);
        if (IgnoredArtifactFiles.Contains(fileName))
            return true;

        var segments = relativePath.Split('/', StringSplitOptions.RemoveEmptyEntries);
        return segments.Any(s => IgnoredArtifactDirectories.Contains(s));
    }
}
